### PR TITLE
luci-app-turboacc:Canonical front-end code

### PR DESCRIPTION
**Pull request by zxlhhyccc**

### CODE REVIEW

**Comment by 1715173329** [comment]
Why? I don't see any point.

**Comment by zxlhhyccc** [comment]
> Why? I don't see any point.

看起来更标准一些吧。。。

**Comment by 1715173329** [comment]
I don't think this is more "standard". We have it put separate directory, and it's enough.

**Comment by zxlhhyccc** [comment]
> I don't think this is more "standard". We have it put separate directory, and it's enough.

我的意思是：其他插件都以插件名称命名，这个也遵循一下。。。

**Comment by 1715173329** [comment]
This is duplicate, the dir name is "turboacc", then you repeated it again in file name, just stop the mess.

**Comment by zxlhhyccc** [comment]
> This is duplicate, the dir name is "turboacc", then you repeated it again in file name, just stop the mess.

绝大部分插件的后缀为htm均是以xxxx_status.htm命名。。。。

**Comment by 1715173329** [comment]
It doesn't make sense, mate.

**Pull request closed without merging**
