### PR TITLE
luci-mod-network: backport 802.11ax HE support

### PR DESCRIPTION
**Pull request by AmadeusGhost**
Can someone test this commit?

### CODE REVIEW

**Comment by AngelaCooljx** [comment]
I can test it later.

**Comment by AngelaCooljx** [comment]
I built immoralwrt-luci-18.06 with this patch #36  for my machine (Xiaomi CR6608).
AX mode showed. 2.4G is normal. 

But there's no channel choice in 5G setting page.

The problem has been mentioned in official repository‘s master branch in this issue [https://github.com/openwrt/luci/issues/5106](url) and actually solved in this commit [https://github.com/openwrt/luci/commit/fb82e03635d9ea43d3f99f219dcdf2222c4aa675](url).

**Comment by AmadeusGhost** [comment]
> The problem has been mentioned in official repository‘s master branch in this issue https://github.com/openwrt/luci/issues/5106 and actually solved in this commit https://github.com/openwrt/luci/commit/fb82e03635d9ea43d3f99f219dcdf2222c4aa675.

Thanks, I‘ll backport it later. By the way, do you have an ax device and can test whether the place shown in the figure below is normal?
htm

**Comment by AngelaCooljx** [comment]
Sorry for my careless test, I found that after flashing this firmware, just doing one step --click "save" button on 5G setting page, the channel choices become normal.

Everything is OK now.

 The figure below is normal. 1200Mbps

**Comment by AmadeusGhost** [comment]
> Sorry for my careless test, I found that after flashing this firmware, just doing one step --click "save" button on 5G setting page, the channel choices become normal.

Thank you very much for your test. No need to be sorry, the default display on luci is indeed problematic, because it does not recognize the newly added 'band' option.

**Comment by AmadeusGhost** [comment]
> But there's no channel choice in 5G setting page.

Fixed.

**Review by 1715173329 — APPROVED** [review]
LGTM

**Pull request merged**
