### PR TITLE
 luci-app-turboacc：use old extra_command wrapper

### PR DESCRIPTION
**Pull request by zxlhhyccc**

### CODE REVIEW

**Comment by 1715173329** [comment]
This is deprecated.

**Comment by zxlhhyccc** [comment]
> This is deprecated.

不修改为旧的兼容，单独运行bash turboacc，会提示没找到东东：
image

**Comment by 1715173329** [comment]
Why? It's not for bash.

**Comment by zxlhhyccc** [comment]
> Why? It's not for bash.
sh同样的问题：
image

**Comment by 1715173329** [comment]
Plz execute it directly, ./turboacc

**Comment by zxlhhyccc** [comment]
> Plz execute it directly, ./turboacc

image

**Comment by 1715173329** [comment]
I have no idea what to say, but please stop this meaningless topic.
You won't need to execute this manually.

**Pull request closed without merging**
