### PR TITLE
Add luci-app-cloudflared

### PR DESCRIPTION
**Pull request by animegasan**
Application for cloudflared settings via LuCI

**Preview Base settings**
image

**Preview Logs**
image

### CODE REVIEW

**Comment by 1715173329** [comment]
Please submit your PR to upstream OpenWrt, thanks.
And this luci is written by yourself, right? Please simply assign the copyright to yourself.

**Comment by animegasan** [comment]
Is there anything I need to edit?
> Please submit your PR to upstream OpenWrt, thanks.

Yes, I will send my PR to OpenWrt upstream

> And this luci is written by yourself, right?

I was inspired by luci-app-zerotier

> Please simply assign the copyright to yourself.

I don't understand this one

**Comment by 1715173329** [comment]
> I don't understand this one

https://github.com/immortalwrt/luci/pull/382/files#diff-699871a172e46bc90f64794d89c2b1471a1f392479a1d4ae86ea83b16cdcc95eR3

for example, `# Copyright (C) 2024 Hilman Maulana <hilman0.0maulana@gmail.com>`

**Comment by animegasan** [comment]
> > I don't understand this one
> 
> https://github.com/immortalwrt/luci/pull/382/files#diff-699871a172e46bc90f64794d89c2b1471a1f392479a1d4ae86ea83b16cdcc95eR3
> 
> for example, `# Copyright (C) 2024 Hilman Maulana <hilman0.0maulana@gmail.com>`

Oh I see, okay

**Review by animegasan — COMMENTED** [review]
Update Copyright

**Pull request closed without merging**
